echo "=== blur_entry.json Verification ==="
echo ""
echo "File location: C:\Users\hmicr\ngsl-samples\blur_entry.json"
echo "File size:" $(wc -c < blur_entry.json) "bytes"
echo "File lines:" $(wc -l < blur_entry.json) "lines"
echo ""
echo "Entry Information:"
echo "- Word: blur"
echo "- POS: 動詞・名詞 (Verb and Noun)"
echo "- IPA: /blɝ/"
echo "- Level: B1"
echo ""
echo "Forms Included:"
echo "1. Plural (noun): blurs /blɝz/"
echo "2. 3rd person singular: blurs /blɝz/"
echo "3. Past tense: blurred /blɝd/"
echo "4. Past participle: blurred /blɝd/"
echo "5. Present participle: blurring /ˈblɝɪŋ/"
echo ""
echo "Each form contains:"
echo "- Type and label"
echo "- Accurate US IPA pronunciation"
echo "- 2 Minecraft context example sentences (English)"
echo "- Japanese translations"
echo "- Full sentence IPA with linking and weak forms"
echo "- Linking descriptions (2-4 points in Japanese)"
echo "- Kana representations reflecting actual pronunciation"
echo ""
echo "Total elements:"
grep -o '"type":' blur_entry.json | wc -l | xargs echo "- Form types (should be 5):"
grep -o '"examples":' blur_entry.json | wc -l | xargs echo "- Example blocks (should be 10):"
